docker run -p 8000:8000 \
  -e OPENAI_API_KEY=$OPENAI_API_KEY \
  -e ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY \
  -e OPENAI_BASE_URL=$OPENAI_BASE_URL \
  -e ANTHROPIC_BASE_URL=$ANTHROPIC_BASE_URL \
  -e VLLM_ENDPOINT=$VLLM_ENDPOINT \
  llm-app:latest
